"""CompositeRecommenders package"""
from CompositeRecommenders.CompositeRecommenders import LSAEndowedSMR
from CompositeRecommenders.CompositeRecommenders import LSAEndowedSMR
from CompositeRecommenders.CompositeRecommenders import CompositeRecommender
