"""ChernoffFace package"""

from ChernoffFace.ChernoffFunctions import chernoff_face
from ChernoffFace.ChernoffFunctions import figure_to_image
from ChernoffFace.ChernoffFace import chernoff_face_auto_colors
from ChernoffFace.ChernoffFace import single_chernoff_face
from ChernoffFace.ChernoffFace import variables_rescale
from ChernoffFace.DataLoaders import load_usa_arrests_data_frame
from ChernoffFace.DataLoaders import load_employee_attitude_data_frame
